// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID          int32
	UserID      pgtype.Int4
	Value       int32
	Type        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID          int32
	Name        string
	Email       string
	Password    string
	CreditLimit int32
	Balance     int32
}
