// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Transaction struct {
	ID          int32
	Value       int32
	Type        string
	Description sql.NullString
	CreatedAt   time.Time
}

type User struct {
	ID          int32
	Name        string
	CreditLimit int32
	Balance     int32
}
